services:
  gamecafe:
    image: ghcr.io/tannerstephens/gamecafe:latest
    restart: unless-stopped
    environment:
      - DATABASE_URI=postgresql+psycopg://postgres:changeme@database:5432/postgres
      - SECRET_KEY=
    volumes:
      - gamecafe-data:/data
    ports:
      - 80:80
  database:
    image: postgres
    restart: unless-stopped
    shm_size: 128mb
    environment:
      - POSTGRES_PASSWORD=changeme
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:5432:5432

volumes:
  postgres-data:
  gamecafe-data:
