"""empty message

Revision ID: c95c7c298bd4
Revises: d39a3752f12b
Create Date: 2025-03-16 04:10:27.395001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c95c7c298bd4'
down_revision: Union[str, None] = 'd39a3752f12b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('publishers',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('bgg_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bgg_id')
    )
    op.create_table('publisher_game_table',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('publisher_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['publisher_id'], ['publishers.id'], ),
    sa.PrimaryKeyConstraint('game_id', 'publisher_id')
    )
    op.add_column('games', sa.Column('name', sa.String(), nullable=False))
    op.add_column('games', sa.Column('bgg_id', sa.Integer(), nullable=False))
    op.add_column('games', sa.Column('image_path', sa.String(), nullable=True))
    op.add_column('games', sa.Column('location', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'games', ['bgg_id'])
    op.drop_column('games', 'title')
    op.drop_column('games', 'publisher')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('publisher', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('games', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'games', type_='unique')
    op.drop_column('games', 'location')
    op.drop_column('games', 'image_path')
    op.drop_column('games', 'bgg_id')
    op.drop_column('games', 'name')
    op.drop_table('publisher_game_table')
    op.drop_table('publishers')
    # ### end Alembic commands ###
